apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplica
  labels: 
    app: app
    type: front-end
spec:
 template:
   metadata:
    name: mypod
    labels: 
      app: web
      type: front-end
   spec:
    containers:
     - name: nginx-cont
       image: nginx:latest
 replicas: 3
 selector:
    matchLabels:
      type: front-end
